"""add_roles_and_emotions

Revision ID: 9bb4261614e7
Revises: 
Create Date: 2026-01-07 17:18:58.896072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb4261614e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'PSYCHOLOGIST', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('psychologist_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('linked_psychologist_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['psychologist_code'])
    op.create_foreign_key(None, 'users', 'users', ['linked_psychologist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'linked_psychologist_id')
    op.drop_column('users', 'psychologist_code')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
