"""add_user_settings_fields

Revision ID: 9e3a4b5ab0d3
Revises: add_file_fields_to_messages
Create Date: 2026-02-02 12:37:38.932531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3a4b5ab0d3'
down_revision: Union[str, Sequence[str], None] = 'add_file_fields_to_messages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.drop_column('users', 'language')
    op.drop_column('users', 'social_links')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
